#server:
#  port: 8888
#
#spring:
#  application:
#    name: cloud-sso
#  profiles:
#    active: dev
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/db4?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
#    username: root
#    password: 2022201529
#    driver-class-name: com.mysql.jdbc.Driver
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: [stat,wall,log4j]
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    # 切换Druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#      config:
#        server-addr: localhost:8848
#        file-extension: yaml
#
#mybatis:
#  config-location: classpath:sqlMapConfig.xml
#  mapper-locations: classpath:mapper/*.xml
#
#logging:
#  level:
#    com.dk.api: debug
#
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 60000
#        readTimeout: 60000
#        loggerLevel: FULL # 日志级别